FROM node:14.15-alpine

ENV PORT 3000

ARG NEXT_PUBLIC_APPOINTMENTS_URL=${NEXT_PUBLIC_APPOINTMENTS_URL}
ENV NEXT_PUBLIC_APPOINTMENTS_URL=${NEXT_PUBLIC_APPOINTMENTS_URL}

ARG NEXT_PUBLIC_REVIEWS_URL=${NEXT_PUBLIC_REVIEWS_URL}
ENV NEXT_PUBLIC_REVIEWS_URL=${NEXT_PUBLIC_REVIEWS_URL}

ARG NEXT_PUBLIC_OCCASION_URL=${NEXT_PUBLIC_OCCASION_URL}
ENV NEXT_PUBLIC_OCCASION_URL=${NEXT_PUBLIC_OCCASION_URL}

ARG NEXT_PUBLIC_SERVICES_URL=${NEXT_PUBLIC_SERVICES_URL}
ENV NEXT_PUBLIC_SERVICES_URL=${NEXT_PUBLIC_SERVICES_URL}

ARG NEXT_PUBLIC_CONTACT_URL=${NEXT_PUBLIC_CONTACT_URL}
ENV NEXT_PUBLIC_CONTACT_URL=${NEXT_PUBLIC_CONTACT_URL}

# Create app directory
RUN mkdir -p /usr/src/app
WORKDIR /usr/src/app

# Installing dependencies
COPY package*.json /usr/src/app/
RUN npm install

# Copying source files
COPY . /usr/src/app

# Building app
RUN npm run build
EXPOSE 3000

# Running the app
CMD "npm" "start"